name: minqlxtended build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.11", "3.10"]
        os: ["ubuntu-22.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python v${{ matrix.python-version }}
        run: |
          sudo apt-get install python${{ matrix.python-version }}-dev
          sudo update-alternatives --install /usr/bin/python3 python3 `which python${{ matrix.python-version }}` 1
          sudo update-alternatives --install /usr/bin/python3-config python3-config `which python${{ matrix.python-version }}-config` 1
      - name: Make
        run: make
